"""surelyai full schema

Revision ID: fcfbcce82952
Revises: 
Create Date: 2026-04-02 19:31:46.823812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfbcce82952'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('RAIN', 'CURFEW', 'STRIKE', 'AQI', name='eventtype'), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('primary_zone', sa.String(), nullable=True),
    sa.Column('persona_type', sa.Enum('FOOD', 'GROCERY', 'ECOMMERCE', name='personatype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    op.create_index(op.f('ix_workers_phone'), 'workers', ['phone'], unique=True)
    op.create_table('platform_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('platform_type', sa.Enum('SWIGGY', 'ZOMATO', 'BLINKIT', 'ZEPTO', 'AMAZON', 'OTHER', name='platformtype'), nullable=False),
    sa.Column('avg_weekly_hours', sa.Float(), nullable=False),
    sa.Column('avg_weekly_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('platform_type', sa.Enum('SWIGGY', 'ZOMATO', 'BLINKIT', 'ZEPTO', 'AMAZON', 'OTHER', name='platformtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('network_location_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'LAPSED', 'CANCELLED', name='policystatus'), nullable=True),
    sa.Column('max_weekly_coverage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_fraud_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=True),
    sa.Column('expected_claim_count', sa.Integer(), nullable=True),
    sa.Column('deviation_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'FALSE_POSITIVE', name='fraudalertstatus'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['external_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='cyclestatus'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('weekly_premium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('risk_components', sa.JSON(), nullable=True),
    sa.Column('expected_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disruption_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('RAIN', 'CURFEW', 'STRIKE', 'AQI', name='eventtype'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['weekly_cycles.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('disruption_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PAID', name='claimstatus'), nullable=True),
    sa.Column('claimed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('fraud_signal_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['weekly_cycles.id'], ),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruption_events.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=True),
    sa.Column('payment_ref', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    op.drop_table('claims')
    op.drop_table('disruption_events')
    op.drop_table('weekly_cycles')
    op.drop_table('zone_fraud_alerts')
    op.drop_table('policies')
    op.drop_table('platform_activity')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_workers_phone'), table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.drop_table('workers')
    op.drop_table('external_events')
    # ### end Alembic commands ###
